### ISSUE TITLE
no crontab for ec2-user

### ISSUE THREAD

**Issue by anhntk54** [yii2tech/crontab#13]
I am using your library. I'm running on my localhost very good but I pushed the project onto Amazon's EC2 server is not operational. Amazon server I still get cron job. So I need to do to run your library?

**Comment by klimov-paul** [comment]
This extension works around `crontab` console command. In order to function your server should satisfy the [requirements](https://github.com/yii2tech/crontab#requirements).
You should ask elsewhere what is needed to setup crontab at Amazon EC2.
