### ISSUE TITLE
En-/disable cronjobs

### ISSUE THREAD

**Issue by hkeio** [yii2tech/crontab#14]
Hi,

is there any possibility to just en- or disable cronjobs that I'm missing?
I don't want to remove some cronjob so disabling would be a nice feature I think. I think it could be made by commenting out the specific line.

**Comment by klimov-paul** [comment]
Crontab config does not provide aby possibilities of disabling/enabling particular lines.
You should either comment/uncomment they in `crontab -e` or at the PHP script, which generates crontab.
You may as well save crontabs into a sifferent files and apply them at will.
