### ISSUE TITLE
Cannot exec command in applyFile() method

### ISSUE THREAD

**Issue by alyushkasm** [yii2tech/crontab#15]
https://github.com/yii2tech/crontab/blob/7ff99d47e61de730071a693874d26b1d3abad4af/CronTab.php#L187
During execution the line above Exception thrown:
Exception 'yii\base\Exception' with message 'Failure to setup crontab from file '/app/runtime/yii2tech_crontab_CronTabelnneF': BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.

Usage: crontab [-c DIR] [-u USER] [-ler]|[FILE]

        -c      Crontab directory
        -u      User
        -l      List crontab
        -e      Edit crontab
        -r      Delete crontab
        FILE    Replace crontab by FILE ('-': stdin)'

in /app/vendor/yii2tech/crontab/CronTab.php:190

I tried to execute the command manually crontab < '/app/runtime/yii2tech_crontab_CronTabelnneF' 2>&1. As a result I got the same message.

If I change the command to
$command = $this->binPath . ' ' . escapeshellarg($filename) . ' 2>&1';
the code works with no exception, and file was merged to crontab.

According to crontab documentation:
Usage: crontab [-c DIR] [-u USER] [-ler]|[FILE]
There is no '<'.

**Comment by klimov-paul** [comment]
See https://github.com/yii2tech/crontab/pull/1

**Comment by alyushkasm** [comment]
I saw your commit. How can I solve my issue?

**Comment by klimov-paul** [comment]
I can not say. I am unable to reproduce your problem. According to numerous testimonials current code should work fine. Try to solve the problem inside your environment.
