### ISSUE TITLE
Failure to setup crontab from file

### ISSUE THREAD

**Issue by ctooley21** [yii2tech/crontab#18]
### What steps will reproduce the problem?
Apply CronTab as Apache user.
### What is the expected result?
CronTab successfully applies changes.
### What do you get instead?
Exception 'yii\base\Exception' with message 'Failure to setup crontab from file '/var/www/html/dev/console/runtime/yii2tech_crontab_CronTabxmc64I': crontab: usage error: file name must be specified for replace
### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.0.4
| Yii Framework Version | 2.0.32-dev
| PHP version           |  7.2.24
| Operating system      | Linux 4.14.158-129.185.amzn2.x86_64 x86_64 (ec2 instance)

**Comment by ctooley21** [comment]
I originally was getting an error about the apache user not having a crontab, but I was able to create one doing the following:
`sudo crontab -u apache -e` and saving.
Now I get the above listed error. Please @ me if there is any extra steps/info I can share.

Note: This may be a wider error, as I was able to reproduce with the general ec2-user that AWS provides. So its not specific to apache (which cannot login, but ec2-user can)

**Comment by ctooley21** [comment]
I am still investigating the core issue, but I am starting to think it may be a permissions issue. The temporary crontab files are being saved with owner root, while I am running the command as ec2-user/apache. Both of which may not have permissions to read the file.

**Comment by ctooley21** [comment]
Got it! Ended up not being a file permission. Looks like the cron implementation on my OS doesn't like the following:
`$command = $this->composeBaseCommand() . ' < ' . escapeshellarg($filename) . ' 2>&1';`
but works when you delete the ' < '
`$command = $this->composeBaseCommand() . ' ' . escapeshellarg($filename) . ' 2>&1';`
On line 198 for CronTab.php

**Comment by lav45** [comment]
the same problem with alpine linux

after execution
flag -r - remove crontab file
```php
class CronTab extends Component
{
    public function removeAll()
    {
        $command = $this->composeBaseCommand() . ' -r 2>&1';
        exec($command);
        return $this;
    }
}
```

when trying to get the contents of a crontab file
```php
    public function getCurrentLines()
    {
        $command = $this->composeBaseCommand() . ' -l 2>&1';
```
returns an error
```sh
Exception 'yii\base\Exception' with message 'Unable to read crontab: crontab: can't open 'www-data': No such file or directory'

in /var/www/vendor/yii2tech/crontab/src/CronTab.php:178
```
or
```sh
~$ docker run --rm -it alpine:3.14 crontab -u www-data -l    
crontab: can't open 'www-data': No such file or directory
```

fix: this command clears the crontab file, not deletes it
```sh
~$ echo | crontab -
```

it is worth putting the command line template into a variable that can be redefined
for example, like here https://github.com/yiisoft/yii2/blob/master/framework/web/AssetConverter.php#L37

```php
class CronTab extends Component
{
  public $commands = [
    'remove' => '{crontab} {user} -r 2>&1',
    'apply' => '{crontab} {user} < {file} 2>&1',
    'current' => '{crontab} {user} -l 2>&1',
  ];
}
```

**Comment by klimov-paul** [comment]
This package has been abandoned. See: https://www.patreon.com/posts/60968716
